name: albums_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  async: ^2.11.0
  build_runner: ^2.4.11
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  get: ^4.6.6
  google_fonts: ^6.2.0
  http: ^1.2.1
  intl: ^0.19.0
  meta: ^1.12.0
  riverpod_annotation: ^2.3.5


dev_dependencies:
  
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  test: ^1.25.2

flutter:
  uses-material-design: true

  assets:
    - assets/img/
